# Generated by Django 5.1.1 on 2024-09-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_reservationhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationhistory',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Подтвержден'), (2, 'Отменен')], verbose_name='Статус бронирования'),
        ),
    ]
