# Generated by Django 5.1.1 on 2024-09-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservationhistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ресторана')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание ресторана')),
                ('preview', models.ImageField(upload_to='booking/services_photos/', verbose_name='Фото услуги')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Подтвержден'), (2, 'Отменен'), (3, 'Ожидание')], default=3, verbose_name='Статус бронирования'),
        ),
        migrations.DeleteModel(
            name='ReservationHistory',
        ),
    ]
