# Generated by Django 5.1.1 on 2024-09-28 13:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_services_options_alter_services_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.PositiveIntegerField(choices=[(1, '12:00'), (2, '13:00'), (3, '14:00'), (4, '15:00'), (5, '16:00'), (6, '17:00'), (7, '18:00'), (8, '19:00'), (9, '20:00'), (10, '21:00'), (11, '22:00')], default=1, verbose_name='Время бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateField(default=datetime.datetime.now, validators=[django.core.validators.MinValueValidator(datetime.datetime.now), django.core.validators.MaxValueValidator(datetime.datetime(2024, 10, 12, 18, 33, 46, 823191))], verbose_name='Дата бронирования'),
        ),
    ]
