# Generated by Django 5.1.1 on 2024-09-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_reservation_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(choices=[('12:00:00', '12:00:00'), ('13:00:00', '13:00:00'), ('14:00:00', '14:00:00'), ('15:00:00', '15:00:00'), ('16:00:00', '16:00:00'), ('17:00:00', '17:00:00'), ('18:00:00', '18:00:00'), ('19:00:00', '19:00:00'), ('20:00:00', '20:00:00'), ('21:00:00', '21:00:00'), ('22:00:00', '22:00:00')], default='12:00:00', verbose_name='Время бронирования'),
        ),
    ]
