# Generated by Django 5.1.1 on 2024-09-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_reservation_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.CharField(choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default='12:00', verbose_name='Время бронирования'),
        ),
    ]
