# Generated by Django 5.1.1 on 2024-09-30 06:04

import booking.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_reservation_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, validators=[booking.validators.validate_start_date], verbose_name='Дата бронирования'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('table', 'start_date', 'start_time')},
        ),
    ]
