# Generated by Django 5.1.1 on 2024-09-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_reservation_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания бронирования'),
        ),
    ]
