# Generated by Django 5.1.1 on 2024-10-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='image',
            field=models.ImageField(blank=True, upload_to='booking/table_images/', verbose_name='Изображение  стола'),
        ),
    ]
